using Nest;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Actions = OpenQA.Selenium.Interactions.Actions;

namespace HT_Design_Pattern.PageObjects
{
    public class InboxPage : BasePage
    {
        public InboxPage(IWebDriver browser) : base("", browser)
        {
        }

        //TODO long and autogenerated xpath
        public Button CommposeBox => new Button(driver.FindElement(By.XPath("//div[@jscontroller='eIu7Db']")));

        public WebDriverWait wait => new WebDriverWait(driver, TimeSpan.FromSeconds(30));

        
        public TextBox SenderMailField => new TextBox(driver.FindElement(By.CssSelector("input[role=combobox]")));
        
        public TextBox SubjectField => new TextBox(driver.FindElement(By.Name("subjectbox")));
        
        public TextBox TextBoxField => new TextBox(driver.FindElement(By.XPath("//div[@aria-label='Message Body']")));

        //public IWebElement SaveCloseField => driver.FindElement(By.XPath("//img[@alt='Close']"));
        public Button SaveCloseButton => new Button(driver.FindElement(By.XPath("//img[@alt='Close']")));


        public void Compose(string senderMail, string subject, string textbox)
        {
            // wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(CommposeBoxField));
            // CommposeBox = new Button(CommposeBoxField);
            CommposeBox.Click();
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(driver.FindElement(By.CssSelector("input[role=combobox]"))));
            SenderMailField.SendKeys(senderMail);
            SubjectField.SendKeys(subject);
            TextBoxField.SendKeys(textbox);

            SaveCloseButton.Click();
        }



    }
}
